### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by RandunuK** [surajitsarkar19/react-native-radial-gradient#7]
I've installed package using `npm install react-native-radial-gradient --save` and tried to linking with `react-native link react-native-radial-gradient`. Below I've mentioned the error.

rnpm-install ERR! Something went wrong while linking. Error: Expected "/* Begin ", "/*", "\"", "}", or [A-Za-z0-9_.] but "<" found.
Please file an issue here: https://github.com/facebook/react-native/issues

Expected "/* Begin ", "/*", "\"", "}", or [A-Za-z0-9_.] but "<" found.

SyntaxError: Expected "/* Begin ", "/*", "\"", "}", or [A-Za-z0-9_.] but "<" found.
    at peg$buildStructuredError (<project_dir>\lms-mobile-app\node_modules\xcode\lib\parser\pbxproj.js:412:12)
    at Object.peg$parse [as parse] (<project_dir>\lms-mobile-app\node_modules\xcode\lib\parser\pbxproj.js:1886:11)
    at pbxProject.parseSync (<project_dir>\lms-mobile-app\node_modules\xcode\lib\pbxProject.js:46:24)
    at isInstalled (<project_dir>\lms-mobile-app\node_modules\react-native\local-cli\link\ios\isInstalled.js:19:60)
    at Object.isInstalled (<project_dir>\lms-mobile-app\node_modules\react-native\local-cli\link\ios\common\isInstalled.js:8:5)
    at Object.keys.forEach.platform (<project_dir>\lms-mobile-app\node_modules\react-native\local-cli\link\link.js:57:36)
    at Array.forEach (<anonymous>)
    at linkDependency (<project_dir>\lms-mobile-app\node_modules\react-native\local-cli\link\link.js:44:32)

--
I'm using following versions
react-native-cli: 1.2.0
react-native: 0.57.1

**Comment by trickyc0d3r** [comment]
update RN to ^0.59 and no problems =)
use rn-diff
